"""
Safety utilities: Red flag scanning, PII redaction, and clinical disclaimers.

Per CLAUDE.md:
- Every agent output must be scanned for 'Red Flags' (suicide risk, sepsis shock).
  If found, immediately override with an emergency referral message.
- PII (SSN, phone, email, MRN) must be redacted before any output is stored or displayed.
"""

import re
from typing import Any, Dict, List


# --- Red Flag Detection ---

# Each entry: (pattern, flag_label)
_RED_FLAG_PATTERNS: List[tuple] = [
    (re.compile(r"\b(suicid\w*|self[- ]?harm|kill\s+(my|him|her|them)self)\b", re.IGNORECASE), "Suicide/Self-Harm Risk"),
    (re.compile(r"\b(septi[ck]\s*shock|sepsis|lactate\s*>\s*[4-9]|lactate\s*[5-9]\.?\d*)\b", re.IGNORECASE), "Sepsis/Septic Shock"),
    (re.compile(r"\b(anaphyla\w+)\b", re.IGNORECASE), "Anaphylaxis"),
    (re.compile(r"\b(cardiac\s*arrest|asystole|pulseless|ventricular\s*fibrillation|v[- ]?fib)\b", re.IGNORECASE), "Cardiac Arrest"),
    (re.compile(r"\b(acute\s*(ischemic\s*)?stroke|cerebrovascular\s*accident|CVA|hemipleg\w+)\b", re.IGNORECASE), "Acute Stroke"),
    (re.compile(r"\b(tension\s*pneumothorax)\b", re.IGNORECASE), "Tension Pneumothorax"),
    (re.compile(r"\b(status\s*epilepticus)\b", re.IGNORECASE), "Status Epilepticus"),
]

_EMERGENCY_REFERRAL_TEMPLATE = (
    "EMERGENCY OVERRIDE: {flags_str}. "
    "This case requires IMMEDIATE emergency medical attention. "
    "Contact emergency services (911) or the nearest emergency department. "
    "This AI system is not a substitute for emergency medical care."
)


def scan_for_red_flags(text: str) -> Dict[str, Any]:
    """
    Scan text for clinical red flags that require emergency intervention.

    Args:
        text: The clinical text to scan.

    Returns:
        Dict with keys:
            flagged (bool): Whether any red flag was detected.
            flags (List[str]): List of detected flag labels.
            emergency_message (str): Override message if flagged, else empty.
    """
    detected_flags: List[str] = []

    for pattern, label in _RED_FLAG_PATTERNS:
        if pattern.search(text):
            if label not in detected_flags:
                detected_flags.append(label)

    flagged = len(detected_flags) > 0
    emergency_message = ""

    if flagged:
        flags_str = ", ".join(detected_flags)
        emergency_message = _EMERGENCY_REFERRAL_TEMPLATE.format(flags_str=flags_str)

    return {
        "flagged": flagged,
        "flags": detected_flags,
        "emergency_message": emergency_message,
    }


# --- PII Redaction ---

_PII_PATTERNS = [
    # SSN: 123-45-6789
    (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "[REDACTED_SSN]"),
    # Phone: (555) 123-4567 or 555-123-4567
    (re.compile(r"\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}"), "[REDACTED_PHONE]"),
    # Email
    (re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"), "[REDACTED_EMAIL]"),
    # MRN: followed by digits (e.g., "MRN: 12345678")
    (re.compile(r"MRN:\s*\d+"), "[REDACTED_MRN]"),
]


def redact_pii(text: str) -> str:
    """
    Redact Protected Health Information (PHI/PII) from text.

    Handles SSN, phone numbers, email addresses, and MRNs.

    Args:
        text: The text potentially containing PII.

    Returns:
        Text with PII replaced by redaction placeholders.
    """
    result = text
    for pattern, replacement in _PII_PATTERNS:
        result = pattern.sub(replacement, result)
    return result


# --- Clinical Disclaimer ---

_DISCLAIMER = (
    "\n\n---\n"
    "DISCLAIMER: This output is generated by an AI clinical decision support "
    "system and is NOT a substitute for professional medical advice, diagnosis, "
    "or treatment. Always consult a qualified healthcare provider for clinical "
    "decisions."
)


def add_disclaimer(output: str) -> str:
    """
    Append a clinical disclaimer to any agent output.

    Args:
        output: The agent's output text.

    Returns:
        The output with a disclaimer appended.
    """
    return output + _DISCLAIMER
